### ISSUE TITLE
[Feature Request] Insert Code Block uses 4 backticks instead of 3. Make this configurable.

### ISSUE THREAD

**Issue by carloscabello** [ieviev/obsidian-keyboard-shortcuts#6]
The _Insert Code Block_ action writes 4 backticks instead of the "traditional" 3. This is probably intended, but I'd like to understand why if possible.

> A code fence is a sequence of at least three consecutive backtick characters (`) or tildes (~). [...]
> The content of the code block consists of all subsequent lines, until a closing code fence of the same type as the code block began with (backticks or tildes), and with at least as many backticks or tildes as the opening code fence.
Source: [Fenced code blocks](https://spec.commonmark.org/0.30/#fenced-code-blocks)

Although defining fenced code blocks by using 4 backticks is correct, I think this should be configurable. In any case, I'd say it would be better if the default was to use 3 backticks (but I know this is personal taste).

The code for this is at `insertCodeBlock` at `quick-snippets-and-navigation/main.js`, but you probably already know this.

Thank you for coding and publishing this plugin by the way.

**Comment by ieviev** [comment]
This was intentional to have code blocks inside the code block.

for example the old Admonition/callout syntax used to look something like this, but there's also other kinds of blocks that are completely open for the developer to extend (mermaid graphs, csv file tables, etc)

![image](https://user-images.githubusercontent.com/36763595/227781921-66930766-76a2-4cef-8761-1c838b33ceef.png)

i probably won't update the extension very soon, but if you need this changed immediately you can go to the plugin directory in the vault (.obsidian/plugins/quick-snippets-and-navigation/main.js)

edit this on line 2990/2992. then when you restart obsidian it should be changed

![image](https://user-images.githubusercontent.com/36763595/227782321-a35076a2-28e8-451d-8ca7-2a5cae6b535c.png)

**Comment by carloscabello** [comment]
Ok, that makes sense. It's actually better this way then.

Amazing. Thanks you for the workaround and explanation. Already got it working.

If I make time, I could try to work on this myself but probably won't be soon either.
